[hooks]
pre-commit = """\
    cargo fmt -- --check \
    && cargo test --all-features --workspace --bins --examples --tests \
    && cargo test --doc \
    && cargo clippy --all-features --workspace --bins --examples --tests -- -D warnings \
    && typos \
"""

[logging]
verbose = true
